### PR TITLE
Added an existing Template

### LINKED ISSUE #1: Add An existing Template
Add an existing Template on the top of which we can make Devgenics Portfolio Site.

### PR DESCRIPTION
**Pull request by himalaya0035**
Fixed #1 
Hi @codeAtNight009 ,
I did exactly what you asked for
I have attached Some images too.
You Maybe wondering how I did it so fast, but I already had digital agency templates with me. 😁
image
image
image

### CODE REVIEW

**Comment by codeAtNight009** [comment]
It is literally too fast, within minutes you did it 😂😂
The template looks fine to me, can you give me the preview link of the template before proceeding further ?

**Comment by himalaya0035** [comment]
Ok Sure !, Just wait a minute

**Comment by himalaya0035** [comment]
Here it is : https://templatemo.com/live/templatemo_563_seo_dream
Check it out

**Comment by codeAtNight009** [comment]
Yes looks fine to me, Done I will merge your Pr
Well done on your task

**Comment by himalaya0035** [comment]
Thanks Man , I appreciate it

**Pull request merged**
